# -*- coding: utf-8 -*-
"""Aula 03

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1li5IksRwJcHY7yVF_UsgZlcJuUrwxHGg
"""

#ETE PORTO DIGITAL
#DISCIPLINA: LPCL
#PROFESSOR: CLOVES
#ESTUDANTE: ?
print('OLÁ, ETE PORTO DIGITAL')